const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const {Element,parse,setWidth,setViewport}=require('./dom-fixture.cjs');
const assets=path.join(__dirname,'../assets'),publicDir=path.join(__dirname,'../public');
class Param{setValueAtTime(v){this.value=v;}linearRampToValueAtTime(v){this.value=v;}exponentialRampToValueAtTime(v){this.value=v;}}
class AudioNode{constructor(){this.frequency=new Param();this.gain=new Param();}connect(){}disconnect(){}start(){}stop(){}}
class AudioContext{constructor(){this.currentTime=0;this.destination={};this.sampleRate=8000;this.state='suspended';}async resume(){this.state='running';}async close(){this.state='closed';}createGain(){return new AudioNode();}createOscillator(){return new AudioNode();}createBufferSource(){return new AudioNode();}createBiquadFilter(){return new AudioNode();}createBuffer(c,n){return{getChannelData:()=>new Float32Array(n)};}}
function setup(width=1280,route='',inlineFile,storageSeed,viewportHeight=680,failMount=false,reducedMotion=false){
 setViewport(width,viewportHeight);const html=fs.readFileSync(inlineFile||path.join(publicDir,route,'index.html'),'utf8');
 const doc=parse(html.replace(/<script[\s\S]*?<\/script>/g,'').replace(/<style[\s\S]*?<\/style>/g,''));doc.createElement=tag=>new Element(tag);doc.getElementById=id=>doc.querySelector('#'+id);doc.documentElement=doc.querySelector('html');doc.body=doc.querySelector('body');
 const win=new Element('window'),microtasks=[],timers=new Map(),frames=new Map(),audio=[],games=[],saved=new Map(storageSeed);let serial=0,frameTime=0;
 const location={href:inlineFile?'file:///test/portfolio.html':'https://osaa601.com/'+route,origin:inlineFile?'null':'https://osaa601.com',hash:''};
 const history={states:[],index:-1,setURL(url){const next=new URL(url,location.href);location.href=next.href;location.hash=next.hash;location.pathname=next.pathname;},replaceState(state,unused,url){if(this.index<0)this.index=0;this.states[this.index]=state;this.setURL(url);},pushState(state,unused,url){this.states=this.states.slice(0,this.index+1);this.states.push(state);this.index++;this.setURL(url);},back(){if(this.index>0){const state=this.states[--this.index];location.hash='#'+state.screen;win.dispatchEvent({type:'popstate',state});}},forward(){if(this.index<this.states.length-1){const state=this.states[++this.index];location.hash='#'+state.screen;win.dispatchEvent({type:'popstate',state});}}};
 Object.assign(win,{requestAnimationFrame:fn=>{const id=++serial;frames.set(id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id),location,history,matchMedia:query=>({matches:query.includes('prefers-reduced-motion')&&reducedMotion,addEventListener(){}}),AudioContext,setInterval:fn=>{const id=++serial;timers.set(id,fn);return id;},clearInterval:id=>timers.delete(id)});
 const warnings=[];const context={window:win,document:doc,location,history,URL,Date,Intl,Map,Set,console:{...console,warn:(...args)=>warnings.push(args[0])},localStorage:{getItem:key=>saved.get(key)??null,setItem:(key,value)=>saved.set(key,value)},setInterval:()=>1,clearInterval(){},queueMicrotask:fn=>microtasks.push(fn),navigator:{clipboard:{writeText:async()=>{}}},CustomEvent:class{constructor(type,data){this.type=type;Object.assign(this,data);}},ResizeObserver:class{observe(){}disconnect(){}}};
 const instrument=()=>{const Audio=win.OsaaAudio.DeskAudio;win.OsaaAudio.DeskAudio=class extends Audio{constructor(o){super(o);audio.push(this);}};if(win.OsaaStarfall){const Engine=win.OsaaStarfall.Engine;win.OsaaStarfall.Engine=class extends Engine{constructor(...args){super(...args);games.push(this);}};}};
 if(inlineFile){for(const match of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)){if(match[1].includes('application/ld+json'))continue;if(match[2].includes('const locales=new Map'))instrument();vm.runInNewContext(match[2],context);}}
 else{for(const file of ['theme-init.js','site.js','desktop-state.js','desktop-extras.js','premium-ui.js','audio.js','starfall-engine.js','starfall-game.js','desktop.js']){if(file==='desktop.js'){instrument();if(failMount)win.OsaaPremium.mount=()=>{throw Error('Expected test startup failure');};}vm.runInNewContext(fs.readFileSync(path.join(assets,file),'utf8'),context,{filename:file});}}
 const q=selector=>{const el=doc.querySelector(selector);assert(el,selector);return el;};const settle=async()=>{await Promise.resolve();await Promise.resolve();while(microtasks.length)microtasks.shift()();};const click=async selector=>{q(selector).click();await settle();};
 const advance=ms=>{frameTime+=ms;const pending=[...frames.values()];frames.clear();for(const fn of pending)fn(frameTime);};
 return {doc,win,q,click,settle,audio,games,timers,frames,advance,location,saved,warnings,history};
}
const current=(test,app)=>test.q('#os-window-'+app).querySelectorAll('.os-view').find(view=>!view.hidden).dataset.page;
if(require.main===module)(async()=>{
 for(const width of [320,768,1024,1280,1920,2560])for(const lang of ['en','ar']){
  const t=setup(width,lang==='ar'?'ar/':''),{q,click}=t;
  assert.equal(t.doc.querySelectorAll('.os-window').length,11);assert.equal(t.audio[0].context,null,'No autoplay');
  assert(q('.os-profile-intro').closest('.os-view'),'Profile banner stays inside the page frame');assert(q('.os-profile-art img').src||q('.os-profile-art img').getAttribute('src'),'Profile banner has its bundled artwork');
  await click('.os-icons [data-app="work"]');const work=q('#os-window-work');
  await click('.os-icons [data-app="services"]');const services=q('#os-window-services');
  await click('[href="#service/cybersecurity"]');assert.equal(current(t,'services'),'service/cybersecurity');
  const projectLinks=q('[data-page="work"]').querySelectorAll('.project-content h3 a');projectLinks[1].click();await t.settle();assert.equal(current(t,'work'),'project/potstation');assert.equal(t.doc.querySelectorAll('.os-window').length,11,'Project stays in the Projects window');assert(!services.hidden&&!work.hidden);
  const serviceVisible=services.querySelectorAll('.os-view').find(v=>!v.hidden);const servicesPosition={left:services.style.left,top:services.style.top};
  await click('#os-window-work [data-nav="back"]');assert.equal(current(t,'work'),'work');assert(!services.hidden&&!work.hidden,'Back cannot hide either open window');assert.equal(current(t,'services'),'service/cybersecurity');assert.equal(serviceVisible.hidden,false);assert.deepEqual({left:services.style.left,top:services.style.top},servicesPosition);
  assert(q('#os-window-work [data-nav="back"]').disabled);await click('#os-window-work [data-nav="forward"]');assert.equal(current(t,'work'),'project/potstation');
  await click('#os-window-services [data-nav="back"]');assert.equal(current(t,'services'),'services');assert.equal(current(t,'work'),'project/potstation');assert(!work.hidden&&!services.hidden);
  await click('#os-window-services [data-nav="forward"]');assert.equal(current(t,'services'),'service/cybersecurity');await click('#os-window-work [data-nav="home"]');assert.equal(current(t,'work'),'work');assert(!services.hidden,'Home is local to this window');
  for(const anchor of q('[data-page="services"]').querySelectorAll('.service-category')){anchor.click();await t.settle();assert.equal(current(t,'services'),anchor.getAttribute('href').slice(1));const page=services.querySelectorAll('.os-view').find(v=>!v.hidden);assert(page.querySelectorAll('.service-offer').length>=5);assert(page.querySelector('a[href^="mailto:"]')||page.querySelector('.button.primary'));await click('#os-window-services [data-nav="home"]');}
  assert.equal(q('[data-page="services"]').querySelectorAll('.service-category').length,7);
  const title=q('#os-window-work .os-drag-title'),beforeDrag=work.style.top;
  title.dispatchEvent({type:'pointerdown',button:0,pointerId:1,clientX:80,clientY:80,bubbles:true,preventDefault(){}});title.dispatchEvent({type:'pointermove',pointerId:1,clientX:80,clientY:64});title.dispatchEvent({type:'pointerup',pointerId:1});assert.notEqual(work.style.top,beforeDrag,'Windows remain draggable');
  await click('#os-window-work [data-action="maximize"]');assert(work.classList.contains('os-maximized'));const maximizedTop=work.style.top;title.dispatchEvent({type:'pointerdown',button:0,pointerId:2,clientX:80,clientY:80,preventDefault(){}});title.dispatchEvent({type:'pointermove',pointerId:2,clientX:80,clientY:150});assert.equal(work.style.top,maximizedTop,'Maximized windows ignore dragging');
  await click('.os-icons [data-app="arcade"]');await click('[data-rpg="overlay"]');const game=t.games[0];assert.equal(game.state.phase,'playing');t.advance(16);const x=game.state.player.x;t.doc.dispatchEvent({type:'keydown',key:'ArrowRight',target:q('.starfall-canvas'),preventDefault(){}});t.advance(40);assert(game.state.player.x>x,'RPG movement is continuous');t.doc.dispatchEvent({type:'keyup',key:'ArrowRight',target:q('.starfall-canvas')});
  const gameVersion=JSON.stringify(game.state);await click('.os-music-toggle');const audio=t.audio[0];audio.context.currentTime=6;for(const fn of t.timers.values())fn();audio.setVolume(.37);audio.toggleMute();audio.toggleSounds();
  const audioVersion=audio.version;for(let n=0;n<6;n++){await click('.os-language');assert.equal(t.audio.length,1);assert.equal(t.games.length,1);assert.equal(audio.version,audioVersion);assert(audio.playing);assert.equal(audio.position,6);assert.equal(audio.volume,.37);assert(audio.muted&&!audio.sounds);assert.equal(audio.listeners.size,1);assert.equal(game.listeners.size,1);assert.equal(JSON.stringify(game.state),gameVersion);assert.equal(t.doc.querySelectorAll('.os-window').length,11);assert.equal(t.doc.events.keydown.length,3);assert.equal(t.frames.size,1);}
  assert.equal(current(t,'services'),'services');assert.equal(current(t,'work'),'work');assert(q('.os-audio-toggle').closest('.os-taskbar'));
  assert(q('#os-window-work').classList.contains('os-maximized'),'Language preserves maximized state');await click('#os-window-work [data-action="maximize"]');assert(!q('#os-window-work').classList.contains('os-maximized'));
  assert.equal(q('.os-profile-art img').src,q('.os-wallpaper').src,'Profile artwork follows the current theme after language changes');await click('.os-theme');assert.equal(q('.os-profile-art img').src,q('.os-wallpaper').src,'Profile artwork follows theme changes');
  await click('#os-window-arcade [data-action="minimize"]');const pausedTime=game.state.time;t.doc.dispatchEvent({type:'keydown',key:'ArrowRight',target:q('.os-start'),preventDefault(){}});t.advance(40);assert.equal(game.state.time,pausedTime,'A minimized game cannot advance');
  const arcadeTask=t.doc.querySelectorAll('.os-task').find(task=>task.getAttribute('aria-controls')==='os-window-arcade');arcadeTask.click();await t.settle();assert(!q('#os-window-arcade').hidden);t.advance(16);t.advance(40);assert(game.state.time>pausedTime,'Active RPG resumes');
  await click('[data-rpg="pause"]');const manualTime=game.state.time;t.advance(40);assert.equal(game.state.time,manualTime);await click('.os-language');t.advance(40);assert.equal(game.state.time,manualTime,'Language preserves a manually paused RPG');assert(game.paused);await click('[data-rpg="overlay"]');t.advance(40);assert(game.state.time>manualTime);
  t.doc.hidden=true;const hiddenTime=game.state.time;t.advance(40);assert.equal(game.state.time,hiddenTime,'Hidden browser tab pauses the RPG');t.doc.hidden=false;
  t.win.dispatchEvent({type:'blur'});const blurredTime=game.state.time;t.advance(40);assert.equal(game.state.time,blurredTime,'Losing browser focus pauses the RPG');t.win.dispatchEvent({type:'focus'});t.advance(16);t.advance(40);assert(game.state.time>blurredTime);
  await click('#os-window-work [data-action="close"]');assert(q('#os-window-work').hidden);assert(!q('#os-window-services').hidden,'Closing Projects leaves Services open');
  // Launcher opens a detail inside its owner; it cannot affect gameplay or music.
  await click('.os-icons [data-app="arcade"]');const searchTime=game.state.time;
  t.doc.dispatchEvent({type:'keydown',key:'k',ctrlKey:true,target:q('.os-start'),preventDefault(){}});assert(!q('.os-search-overlay').hidden);t.advance(40);assert.equal(game.state.time,searchTime);
  const search=q('#os-search-input');search.value=t.doc.documentElement.lang==='ar'?'الأمن السيبراني':'cybersecurity';search.dispatchEvent({type:'input'});assert(q('.os-search-results').querySelectorAll('button').length>0);
  t.doc.dispatchEvent({type:'keydown',key:'Enter',target:search,preventDefault(){}});assert(q('.os-search-overlay').hidden);assert.equal(current(t,'services'),'service/cybersecurity');assert(audio.playing);
  await click('.os-icons [data-app="journal"]');assert.equal(q('[data-page="journal"]').querySelectorAll('.journal-card').length,3);
  await click('[data-page="journal"] [data-bookmark="clear-security-reports"]');await click('[data-journal-filter="saved"]');assert.equal(q('[data-page="journal"]').querySelectorAll('.journal-card').filter(c=>!c.hidden).length,1);
  await click('[data-page="journal"] [href="#note/clear-security-reports"]');assert.equal(current(t,'journal'),'note/clear-security-reports');await click('#os-window-journal [data-nav="back"]');assert.equal(current(t,'journal'),'journal');
  for(const id of ['profile','services','work','creative','journal']){await click('.os-icons [data-app="'+id+'"]');await click('#os-window-'+id+' [data-nav="home"]');await click('[data-collect="'+id+'"]');}
  await click('.os-settings-toggle');assert.equal(current(t,'settings'),'settings');assert(!q('.wallpaper-grid [data-wallpaper="blue"]').disabled);assert(!q('.wallpaper-grid [data-wallpaper="purple"]').disabled);assert(q('.wallpaper-grid [data-wallpaper="starlight"]').disabled);
  await click('.wallpaper-grid [data-wallpaper="purple"]');assert.equal(q('.os-shell').dataset.wallpaper,'purple');await click('.os-language');assert.equal(q('.os-shell').dataset.wallpaper,'purple');assert.equal(q('[data-page="journal"] [data-bookmark="clear-security-reports"]').getAttribute('aria-pressed'),'true');
  const booking=q('.consultation-booking');assert(booking.closest('#os-window-contact'));assert(booking.getAttribute('href').startsWith('mailto:osaa@osaa601.com?'));assert(booking.getAttribute('href').includes('subject='));assert(q('.os-personal-emblem'));assert(q('.welcome-paths').querySelectorAll('.welcome-path').length===3);
  await click('.os-icons [data-app="work"]');const resized=q('#os-window-work'),handle=q('#os-window-work [data-resize="se"]'),sizeBefore={width:parseFloat(resized.style.width),height:parseFloat(resized.style.height)};
  handle.dispatchEvent({type:'pointerdown',button:0,pointerId:7,clientX:100,clientY:100,preventDefault(){}});handle.dispatchEvent({type:'pointermove',pointerId:7,clientX:148,clientY:68});handle.dispatchEvent({type:'pointerup',pointerId:7});assert(parseFloat(resized.style.width)>=sizeBefore.width);assert(parseFloat(resized.style.height)<sizeBefore.height);
  if(width>=700){await click('#os-window-work [data-action="layout"]');assert(!q('#os-window-work .os-window-menu').hidden);await click('#os-window-work [data-window-layout="left"]');assert(parseFloat(resized.style.width)<width/2);assert(q('#os-window-work .os-window-menu').hidden);}
  const geometry={left:resized.style.left,top:resized.style.top,width:resized.style.width,height:resized.style.height};await click('.os-language');assert.deepEqual({left:q('#os-window-work').style.left,top:q('#os-window-work').style.top,width:q('#os-window-work').style.width,height:q('#os-window-work').style.height},geometry);
  game.state.phase='won';game.emit();assert(!q('.wallpaper-grid [data-wallpaper="starlight"]').disabled,'Completing the RPG unlocks Starlight');
  const layout=JSON.parse(t.saved.get('osaa601-desktop-layout'));assert.equal(layout.version,1);assert.equal(layout.windows.length,11);assert(JSON.parse(t.saved.get('osaa601-archive')).favorites.includes('clear-security-reports'));
  await click('.os-music-toggle');assert(!audio.playing);t.win.dispatchEvent({type:'pagehide'});assert.equal(audio.context.state,'closed');
  console.log('PASS '+width+'px '+lang+': histories, audio/RPG continuity, search, journal bookmarks, archive rewards, resizing/snapping, language geometry, and consultation requests.');
 }
 const session=setup(1280);await session.click('.os-icons [data-app="work"]');session.q('.project-content h3 a').click();await session.settle();await session.click('#os-window-work [data-window-layout="right"]');await session.click('#os-window-profile [data-action="minimize"]');session.win.dispatchEvent({type:'pagehide'});
 const restored=setup(1280,'',null,session.saved);await restored.click('.os-settings-toggle');await restored.click('[data-desktop-action="restore"]');assert.equal(current(restored,'work'),'project/security-operations');assert(!restored.q('#os-window-work').hidden);assert(restored.q('#os-window-profile').hidden);assert(parseFloat(restored.q('#os-window-work').style.left)>600);
 await restored.click('.os-settings-toggle');await restored.click('[data-desktop-action="arrange"]');const visible=restored.doc.querySelectorAll('.os-window').filter(w=>!w.hidden);assert(visible.length>=2);assert(visible.every(w=>!w.classList.contains('os-maximized')));
 await restored.click('[data-desktop-action="reset"]');assert.equal(restored.doc.querySelectorAll('.os-window').filter(w=>!w.hidden).length,1);assert(!restored.q('#os-window-profile').hidden);assert(restored.q('[data-desktop-action="restore"]').disabled);console.log('PASS saved-session restoration, arrangement, and reset.');
 for(const route of ['work/potstation/','ar/work/isms/']){const t=setup(1280,route);assert(current(t,'work').startsWith('project/'));await t.click('#os-window-work [data-nav="back"]');assert.equal(current(t,'work'),'work');console.log('PASS direct project route '+route);}
 if(process.env.FULLSCREEN_PREVIEW){const t=setup(1280,'',process.env.FULLSCREEN_PREVIEW);await t.click('.os-icons [data-app="work"]');t.q('.project-content h3 a').click();await t.settle();assert(current(t,'work').startsWith('project/'));await t.click('.os-language');assert(t.location.href.startsWith('file:///'));assert(current(t,'work').startsWith('project/'));console.log('PASS standalone local-file preview.');}
})().catch(error=>{console.error(error);process.exitCode=1;});
module.exports={setup,current};
