const assert=require('assert/strict'),{setup,current}=require('./desktop.test.cjs');
(async()=>{
 for(const [width,height]of [[320,568],[390,844],[768,1024],[1024,768],[1366,768],[1920,1080],[2560,1440],[3440,1440]])for(const lang of ['en','ar']){
  const t=setup(width,lang==='ar'?'ar/':'',null,null,height),{q,click}=t;assert.equal(t.warnings.length,0);assert.equal(t.doc.querySelectorAll('.os-window').length,11);
  await click('.os-hire');assert.equal(current(t,'services'),'services');assert.equal(q('[data-page="services"]').querySelectorAll('[data-commercial-group]').length,3);
  await click('[href="#service/cybersecurity"]');assert.equal(current(t,'services'),'service/cybersecurity');const page=q('[data-page="service/cybersecurity"]');const email=page.querySelector('.scope-cta .button');assert(email.getAttribute('href').startsWith('mailto:osaa@osaa601.com?subject='));assert(decodeURIComponent(email.getAttribute('href')).includes(lang==='ar'?'الأمن السيبراني':'Cybersecurity'));assert(page.querySelector('.service-brief'));assert.equal(q('.engagement-steps').querySelectorAll('li').length,5);
  // Browser Back/Forward restores the owning trail without hiding another app.
  await click('.os-icons [data-app="work"]');q('.project-content h3 a').click();await t.settle();assert.equal(current(t,'work'),'project/security-operations');t.history.back();assert.equal(current(t,'work'),'work');assert(!q('#os-window-services').hidden);t.history.forward();assert.equal(current(t,'work'),'project/security-operations');await click('#os-window-work [data-nav="back"]');assert.equal(current(t,'work'),'work');assert.equal(current(t,'services'),'service/cybersecurity');
  await click('[data-project-filter="professional"]');assert.equal(q('[data-page="work"]').querySelectorAll('.project-card').filter(x=>!x.hidden).length,2);await click('.os-language');assert.equal(q('[data-project-filter="professional"]').getAttribute('aria-pressed'),'true');await click('[data-project-filter="all"]');
  const activeLang=t.doc.documentElement.lang;await click('.os-icons [data-app="journeys"]');assert.equal(current(t,'journeys'),'journeys');assert(q('.journey-status').textContent.includes(activeLang==='ar'?'قيد التخطيط':'In planning'));assert.equal(q('.journey-formats').querySelectorAll('article').length,3);assert.equal(q('.journey-actions a').getAttribute('href'),'#creative');
  await click('.os-icons [data-app="contact"]');assert.equal(q('[data-page="contact"]').querySelectorAll('.inquiry-option').length,6);for(const a of q('[data-page="contact"]').querySelectorAll('.inquiry-option')){const uri=a.getAttribute('href');assert(uri.startsWith('mailto:osaa@osaa601.com?'));assert(uri.includes('body='));assert(!uri.includes('\n'));}assert(q('[download="osaa601-contact.vcf"]'));
  await click('.os-icons [data-app="work"]');q('#os-window-services [data-nav="back"]').focus();assert(q('#os-window-services').classList.contains('os-active'),'Keyboard focus raises the correct window');assert(!q('#os-window-work').hidden);
  await click('.os-search-toggle');assert(q('.os-stage').inert);assert(!q('.os-search-overlay').hidden);assert(q('.os-search-results [aria-pressed="true"]').scrolled);t.doc.dispatchEvent({type:'keydown',key:'Escape',target:q('#os-search-input'),preventDefault(){}});assert(!q('.os-stage').inert);assert(q('.os-search-overlay').hidden);
  await click('.os-icons [data-app="arcade"]');await click('[data-rpg="overlay"]');const game=t.games[0];t.advance(16);const before=game.state.player.x;q('[data-rpg-move="right"]').dispatchEvent({type:'pointerdown',pointerId:91,bubbles:true,preventDefault(){}});t.advance(40);assert(game.state.player.x>before,'Held touch movement works');q('[data-rpg-move="right"]').dispatchEvent({type:'pointerup',pointerId:91,bubbles:true});q('[data-rpg="attack"]').dispatchEvent({type:'pointerdown',pointerId:92,bubbles:true,preventDefault(){}});t.advance(40);assert(game.state.player.attack>0,'Held touch attack works');q('[data-rpg="attack"]').dispatchEvent({type:'pointerup',pointerId:92,bubbles:true});game.save();const existingSave=t.saved.get('osaa601-starfall-save');assert(existingSave);await click('.os-language');assert.equal(t.saved.get('osaa601-starfall-save'),existingSave);assert.equal(t.games.length,1);assert.equal(t.games[0].listeners.size,1);assert.equal(t.frames.size,1);
  t.win.dispatchEvent({type:'pagehide'});console.log('PASS '+width+'×'+height+' '+lang+': client journey, browser/local history, filters, focus, metadata, inquiry links, Future Journeys, and touch/save continuity.');
 }
 for(const [route,owner,screen]of [['services/cybersecurity/','services','service/cybersecurity'],['ar/services/governance-advisory/','services','service/governance-advisory'],['journal/clear-security-reports/','journal','note/clear-security-reports'],['ar/journeys/','journeys','journeys'],['contact/','contact','contact']]){const t=setup(1920,route);assert.equal(current(t,owner),screen);assert(t.location.href.includes(route));assert(t.doc.documentElement.classList.contains('desktop-enhanced'));console.log('PASS direct route '+route);}
 const failure=setup(1280,'',null,null,800,true);assert(!failure.doc.documentElement.classList.contains('desktop-enhanced'));assert.equal(failure.doc.querySelectorAll('.os-shell').length,0);assert(failure.q('.os-rescue').textContent.includes('Work with me'));assert.equal(failure.q('.os-rescue').querySelectorAll('.inquiry-option').length,6);assert.equal(failure.warnings.length,1);console.log('PASS startup-failure fallback with real content and native email actions.');
})().catch(e=>{console.error(e);process.exitCode=1;});
